# Generated by Django 4.2.7 on 2024-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=2, max_length=100, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
